version: '3.5'
services:
  db:
    container_name: datagrabber_db
    image: mdillon/postgis
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    networks:
      - seed

networks:
  seed:
    name: development