DROP DATABASE IF EXISTS data_grabber;
CREATE DATABASE data_grabber;

-- DROP USER IF EXISTS '#DB_USERNAME#';
-- CREATE USER '#DB_USERNAME#' IDENTIFIED BY '#DB_PASSWORD#';
-- GRANT ALL PRIVILEGES ON *.* TO '#DB_USERNAME#' WITH GRANT OPTION;
